### ISSUE TITLE
Add iOS 9 support?

### ISSUE THREAD

**Issue by Johnny5sword** [tristanphan/miru#2]
Hi!

Would it be possible to lower the min OS to iOS 9.3 and also support 32-bit?

My iPad 2 can't be updated anymore so iOS 9.3.5 is its last version.

I've search for other options like [NineAnimator](https://github.com/SuperMarcus/NineAnimator)(iOS 13+) and [Ketsu](https://ketsu.app/)(iOS 12+) but they unfortunately require higher OS versions.

**Comment by tristanphan** [comment]
Hello,

Unfortunately, Flutter (the framework this app hinges on) has a minimum requirement of iOS 11, so I cannot build for any version lower than that.
